### ISSUE TITLE
Is it possible with available header files and c souce codes to generate bare-metal application?

### ISSUE THREAD

**Issue by WazaAbdulkadir** [openhwgroup/core-v-mcu-cli-test#46]
Hello,

I want to create bare-metal implementation. 
I figured out that there are hal_gpio_pulp.c and hal_pinmux1.c source files and they are not containing freeRTOS files.
Looks eligible to use their functions for  bare-metal application.
Also, core-v mcu config file is not included these files, but pulp_io header file is included. This might be a problem.

So I want to ask if it is possible to design bare-metal application with using these files or others using core-v-sdk?

**Comment by MikeOpenHWGroup** [comment]
Hi @WazaAbdulkadir.  While it is technically possible to create a bare-metal platform for CORE-V-MCU and you may be able to use either this repo and/or CORE-V-SDK as a starting point, as far as I am aware, there are no plans to do so.  If this is something your organization is interested in, I suggest reaching out to the OpenHW Group's Software Task Group to see if there would be interest in such a project.

You can find my email address on my GitHub profile and I can put you in touch with the SWTG.
