### ISSUE TITLE
Read switch display on led 

### ISSUE THREAD

**Issue by WazaAbdulkadir** [openhwgroup/core-v-mcu-cli-test#48]
I am trying to read switch value and display it on led using hal functions on nexsys board.

When I read switch value it is always 1 regardless of switch position. 

From debugging I get 
        Hex:0x1116
	Binary:1000100010110

binary value is what **register_value** holds, this shows program accepts gpio_22 as an input. What could be the problem?
Is this the right usage of **hal_read_status_raw**() function.   

Here is my code: 

```
int main(void)
{
    prvSetupHardware();

     // SET LED AS OUTPUT

     hal_setpinmux(21,2);
     hal_set_gpio_mode(14,1);

     // SET SWITCH AS INPUT

     hal_setpinmux(29,2);
     hal_setpullup(29,1);
     hal_set_gpio_mode(22,0);

     uint8_t  switch1        = 0;
     uint32_t register_value = 0;

     hal_write_gpio(14,0);
     while(1){
           
 		hal_read_gpio_status_raw(22,&register_value);
 
 		switch1 = (register_value >> 12) & 0x01;
 		
 		if (switch1==1) {
 			hal_write_gpio(14,1);
 		}

 		else {
 			hal_write_gpio(14,0);

 		}

 	}
}
```

**Comment by gmartin102** [comment]
Assuming you are running on the FPGA emulation platform nexys?  Did you remap and rebuild to move the IO's to connect to the nexys Switches and LEDs?  otherwise the  pins you are controlling are not connected as you expect.

**Comment by WazaAbdulkadir** [comment]
Yes i did it.
Corresponding led is lighting but it is always on.
hal_read input bit always high regardless of switch's status.


27 Mar 2023 Pzt 18:34 tarihinde Greg Martin ***@***.***> şunu
yazdı:

**Comment by WazaAbdulkadir** [comment]
I also tried with using hal_read_gpio_status() still input value is always 1.
Code is below: 

     ```
     hal_setpinmux(21,2);
     hal_set_gpio_mode(14,1);

     // SET SWITCHES AS INPUT

      hal_setpinmux(29,2);
      gpio_hal_typedef switch1;
      switch1.number = 22;
      switch1.mode   = 0 ;


      hal_write_gpio(14,0);
      while(1){

    	  hal_read_gpio_status(&switch1);

 		 if (switch1.in_val = 1) {
 			 hal_write_gpio(14,1);
 		 }
 		 else {
 			 hal_write_gpio(14,0);
 		}
```

**Comment by WazaAbdulkadir** [comment]
This issue will be discussed [here](https://github.com/openhwgroup/core-v-mcu/issues/304)
