### ISSUE TITLE
Programming QSPI Flash

### ISSUE THREAD

**Issue by abdullahyildiz** [openhwgroup/core-v-mcu-cli-test#50]
I would like to program QSPI Flash memory externally. That is, I have an external programmer (which is actually a software running on Raspberry Pi) so that I can program the QSPI Flash memory without applying the steps [here](https://github.com/openhwgroup/core-v-mcu-cli-test/tree/main/cli_test#programming-qspi-flash).

For this, I just take the cli.bin and write to QSPI Flash memory page-wise starting from address zero.

However, I noticed that this method is not working and as I understand, [the programming operation](https://github.com/openhwgroup/core-v-mcu-cli-test/tree/main/cli_test#programming-qspi-flash) uses a different memory write scheme (rather than just incrementing the address for each write operation).

Based on my observations, the flash memory content differs starting from page 256 in Flash memory when I do the programming via the external programming method (instead of the original method).

Is there any description that I can refer to regarding the memory write scheme?

**Comment by MikeOpenHWGroup** [comment]
Hi @abdullahyildiz, thanks for your interest in the CORE-V-MCU.

@gmartin102 and/or @HughOKeeffe1 can either of you point @abdullahyildiz in the right direction?

**Comment by gmartin102** [comment]
@abdullahyildiz - I'm sorry I can't help more, but since it appears your first 64K is programmed correctly (you mentioned differences at page 256) then I would be suspect that something is incorrect in your raspberry pi routine.  you didn't mention what the differences are at page 256, but looking for a pattern might help (swabbing, repeated data, etc). the cli_test has the programming of the SPI embedded in it look at the qspi_tests.c file, specifically the program subroutine that interacts with the spi_load.py script.

**Comment by abdullahyildiz** [comment]
Hi @gmartin102,

Thank you for your support and clarification.

This is what I observe when I apply the programming sequence [here](https://github.com/openhwgroup/core-v-mcu-cli-test/tree/main/cli_test#programming-qspi-flash) and then read back the SPI Flash:

![screenshot_240417_1](https://github.com/openhwgroup/core-v-mcu-cli-test/assets/3716793/56378532-ad08-4b57-b932-bff294ce5d2b)

On left side there is the readback data from flash memory, on the right side, output of `xxd cli.bin` command is shown. As I tried to explain before, the first mismatch occurs at page 0 of the second sector in Flash memory.

**Comment by abdullahyildiz** [comment]
Hi @gmartin102, @MikeOpenHWGroup,

I found the issue. It was my mistake in my flash programmer script.

Before closing the case, would you be interested in sharing my code here?

**Comment by abdullahyildiz** [comment]
Hi @MikeOpenHWGroup,

I share the script below for your review.

[spi_flasher.py.txt](https://github.com/openhwgroup/core-v-mcu-cli-test/files/15020901/spi_flasher.py.txt)
